### PR TITLE
Add Windows CI via AppVeyor

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR!  I'm new to AppVeyor.  Should I create account or add github integration?

**Comment by alagoutte** [comment]
it is like Travis but for Windows :-)

Need to create a account (can be linked with Github) and enable build for nghttp2 repo

**Comment by tatsuhiro-t** [comment]
Thank you.   Will try it out.

**Comment by tatsuhiro-t** [comment]
Works great.  Thank you!

**Pull request merged**
