### PR TITLE
Support for Windows / MinGW

### LINKED ISSUE #363: Windows / MSVC14 support in nghttp2_asio.
I was trying to build nghttp2 and nghttp2_asio using MSVC14 and a simple CMake configuration.

nghttp2 builds fine apart from some integer truncation warnings (e.g. conversion from 'size_t' to 'uint8_t', possible loss of data). I prefer to treat all warnings as errors, though.

nghttp2_asio is another story, since lots of the code seems to use UNIX only functionality (e.g. different "sys/*.h" headers as well as "getopt.h" in "util.h"). Are there any plans to fix nghttp_asio to compile with MSVC14 as well?

Short list of things that I identified, and which would need to be done:
- Fix warnings by introducing explicit casts.
- Add Windows implementation for "memchunk.h", which doesn't use vectored I/O.
- Split up "util.h/cpp" into separate utility files, meaning common utility functions in one file and UNIX specific utility functions for the command line tools in another file. Also porting the command line utilities would be another big task.

### PR DESCRIPTION
**Pull request by dermojo**
Resolve #363 by introducing support for Windows/MinGW

### CODE REVIEW

**Comment by alagoutte** [comment]
Add test on travis ?

**Comment by dermojo** [comment]
I took a look at the current travis/appveyor config and it seems Boost support is currently missing for all platforms. We probably have to build Boost during CI, which isn't trivial (at least MinGW/Windows).
Or is downloading pre-build binary libs an option?

**Comment by tatsuhiro-t** [comment]
Thank you!

**Comment by zwl698** [comment]
Hi!I translated and edited nghttp2_asio windows library version for a long time failed, I ask you if you had a nghttp2_asio library of windows.

**Comment by zwl698** [comment]
Hi! I  compiled  nghttp2_asio windows library version for a long time but failed, I ask you if you had a nghttp2_asio library of windows.

**Pull request merged**
