### PR TITLE
Update minimum CMake version to 3.5

### PR DESCRIPTION
**Pull request by anthonyalayo**
On the latest version of CMake, a warning is emitted if it detects a project using min version < 3.5:
```
CMake Deprecation Warning at build/_deps/nghttp2-src/CMakeLists.txt:25 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

CMake 3.5 was released in March 2016, so having it upgraded seems reasonable:
https://cmake.org/pipermail/cmake/2016-March/062947.html

### CODE REVIEW

**Comment by anthonyalayo** [comment]
cc @tatsuhiro-t

**Comment by anthonyalayo** [comment]
CI checks passed, let me know what you think @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
Thank you for PR.  Merged now.

**Comment by anthonyalayo** [comment]
@tatsuhiro-t when is your next version release of nghttp2 planned?

**Pull request merged**
