### PR TITLE
Deprecate libnghttp2_asio

### PR DESCRIPTION
**Pull request by tatsuhiro-t**

### CODE REVIEW

**Comment by srinarasi** [comment]
@tatsuhiro-t I could not find any discussion on why libnghttp2_asio has been deprecated. I would be grateful if you could explain the reason for its deprecation or point me to an earlier discussion about it. I was considering using it in our application and would like to learn more about its problems.

**Comment by tatsuhiro-t** [comment]
The primary reason is that I have no time to maintain libnghttp2_asio.  If anyone is willing to maintain it, please setup a separate repository to host the code.  I can help doing that.

**Comment by srinarasi** [comment]
I will be glad to maintain it. Are you proposing to create a repository nghttp2 org or host it somewhere else?

**Comment by tatsuhiro-t** [comment]
Thank you.  I can create a dedicated repository under nghttp2 org as a template.  You can fork it under whatever you like.  Alternatively, I can invite you as a collaborator to the repository.

**Comment by srinarasi** [comment]
I prefer keeping the asio support under nghttp2 org itself. So, it would be great if you could add me as a collaborator to the new repository.

**Comment by tatsuhiro-t** [comment]
I'll setup new repository and send an invitation to you when it is ready.

**Comment by tatsuhiro-t** [comment]
@srinarasi I set up https://github.com/nghttp2/nghttp2-asio and sent invitation to you.

**Comment by srinarasi** [comment]
@srinarasi Thanks! I accepted it.

**Comment by patlecat** [comment]
What does this actually mean? Is libnghttp2 not use asio anymore? And if so what is used for networking now?

**Pull request merged**
